# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/hass-hue-icons.js

# Text-to-speech
tts:
  - platform: google_translate

homeassistant:
  ## Packages support enabled - Includes every package that is inside the packages/ directory
  packages: !include_dir_named packages/

# Standart includes
automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

# Manuel includes
alarm_control_panel: !include configs/alarm.yaml
alert: !include configs/alerts.yaml
binary_sensor: !include configs/binary_sensors.yaml
camera: !include configs/cameras.yaml
cover: !include configs/covers.yaml
custom_templates: !include configs/custom_templates.yaml
http: !include configs/http.yaml
mqtt: !include configs/mqtt.yaml
notify: !include configs/notifies.yaml
sensor: !include configs/sensors.yaml
template: !include configs/templates.yaml
vacuum: !include configs/vacuums.yaml
waste_collection_schedule: !include configs/waste_collection_schedule.yaml
zone: !include configs/zones.yaml