# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  
# Text-to-speech
tts:
  - platform: google_translate

http:
  # Allow nginx to reach hass
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 3
  trusted_proxies:
    - 172.20.50.15

# Standart includes
automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

# Manuel includes
camera: !include configs/cameras.yaml
cover: !include configs/covers.yaml
mqtt: !include configs/mqtt.yaml
command_line: !include configs/command_line.yaml