- platform: manual
  name: Home Alarm
  code_arm_required: false
  disarm_after_trigger: false
  disarmed:
    trigger_time: 0
  armed_home:
    arming_time: 0
    delay_time: 5
    trigger_time: 120
  armed_night:
    arming_time: 0
    delay_time: 5
    trigger_time: 120
  armed_away:
    arming_time: 0
    delay_time: 5
    trigger_time: 120

#template
- platform: template
  panels:
    safe_alarm_panel:
      name: Alarmanlage
      unique_id: "alarmanlage"
      code_arm_required: false
      value_template: "{{ states('alarm_control_panel.home_alarm') }}"
      arm_away:
        service: alarm_control_panel.alarm_arm_away
        target:
          entity_id: alarm_control_panel.home_alarm
      arm_home:
        service: alarm_control_panel.alarm_arm_home
        target:
          entity_id: alarm_control_panel.home_alarm
      arm_night:
        service: alarm_control_panel.alarm_arm_night
        target:
          entity_id: alarm_control_panel.home_alarm
      disarm:
        - service: alarm_control_panel.alarm_disarm
          target:
            entity_id: alarm_control_panel.home_alarm
