  garage_door:
    name: "Garage ist geöffnet"
    message: "Achtung! Das Garagentor ist noch geöffnet!"
    done_message: "Das Garagentor wurde geschlossen."
    entity_id: cover.garage_door
    state: "open"   # Optional, 'on' is the default value
    repeat:
      - 10
      - 15
      - 30
      - 60
    can_acknowledge: true  # Optional, default is true
    skip_first: true  # Optional, false is the default
    notifiers:
      - christian_iphone